updated Dockerfile and changed to Bcalms50

diff --git a/Docker/DockerFile b/Docker/DockerFile
--- a/Docker/DockerFile
+++ b/Docker/DockerFile
@@ -8,21 +8,17 @@ MAINTAINER David Koslicki version: 0.1
 RUN apt-get -y update
 RUN apt-get install -y wget
 RUN mkdir jellyfish
-RUN cd jellyfish
-RUN wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.0/jellyfish-2.2.0.tar.gz
-RUN tar -xzf jellyfish-2.2.0.tar.gz
-RUN cd jellyfish-2.2.0
+RUN cd jellyfish && wget https://github.com/gmarcais/Jellyfish/releases/download/v2.2.0/jellyfish-2.2.0.tar.gz && tar -xzf jellyfish-2.2.0.tar.gz
 RUN apt-get install -y g++
-RUN ./configure
 RUN apt-get install -y build-essential
-RUN make
-RUN cd /
+RUN cd /jellyfish/jellyfish-2.2.0/ && ./configure && make
 
 #Install Julia
 RUN apt-get install -y software-properties-common python-software-properties
 RUN add-apt-repository -y ppa:staticfloat/juliareleases
 RUN add-apt-repository -y ppa:staticfloat/julia-deps
-RUN apt-get -y update
+#force zero exit code due to outdated package called wheezy
+RUN apt-get -y update || echo "ok" 
 RUN apt-get install -y julia
 RUN apt-get install -y hdf5-tools
 
@@ -34,12 +30,8 @@ RUN git clone https://github.com/dkoslicki/CommonKmers.git
 RUN julia -e 'Pkg.add("HDF5"); Pkg.add("ArgParse");'
 
 #Install query per sequence
-RUN cd CommonKmers
-RUN cd src
-RUN cd QueryPerSeq
-RUN g++ -I /jellyfish/jellyfish-2.2.0/include -std=c++0x -Wall -O3 -L /jellyfish/jellyfish-2.2.0/.libs -l jellyfish-2.0 -l pthread -Wl,--rpath=/jellyfish/jellyfish-2.2.0/.libs query_per_sequence.cc sequence_mers.hpp -o query_per_sequence
-RUN cp query_per_sequence /usr/local/bin
-RUN cd /
+RUN cd /CommonKmers/src/QueryPerSeq/ && g++ -I /jellyfish/jellyfish-2.2.0/include -std=c++0x -Wall -O3 -L /jellyfish/jellyfish-2.2.0/.libs -l jellyfish-2.0 -l pthread -Wl,--rpath=/jellyfish/jellyfish-2.2.0/.libs query_per_sequence.cc sequence_mers.hpp -o query_per_sequence
+RUN cp /CommonKmers/src/QueryPerSeq/query_per_sequence /usr/local/bin
 
 #Install gzip
 RUN apt-get install -y gzip
