added exit codes

diff --git a/Docker/specific b/Docker/specific
--- a/Docker/specific
+++ b/Docker/specific
@@ -5,12 +5,14 @@
 if [ ! -f "$CONT_FASTQ_FILE_LISTING" ]
 then
 	echo "List of input files not given. Please include a list of input files at: $CONT_FASTQ_FILE_LISTING" 1>&2
+	exit 0
 fi
 
 #check if Data folder is present
-if [ ! -d /dckr/mnt/camiref/Data ]
+if [ ! -d /dckr/mnt/camiref/CommonKmersData ]
 then
-	echo "Data directory missing. Hint, include the following command when starting docker: -v /path/to/local/Data:/dckr/mnt/camiref/Data:ro" 1>&2
+	echo "Data directory missing. Hint, include the following command when starting docker: -v /path/to/local/Data:/dckr/mnt/camiref/CommonKmersData:ro" 1>&2
+	exit 0
 fi
 
 cd /dckr/mnt/input
@@ -20,6 +22,7 @@ do
 	if [ ! -f $file ]
 	then
 		echo "The file $file does not exist. Please make sure it is accessible in /dckr/mnt/input/. Hint, include the following command when starting docker: -v /path/to/input/dir:/dckr/mnt/input:ro" 1>&2
+		exit 0
 	fi
 	#prep and classify sample
 	#decompress
